version: '3.8'

services:
  web:
    build: .
    container_name: gowild_searcher
    ports:
      - "8000:80"
    volumes:
      - ./gowild.db:/code/gowild.db
    environment:
      - TZ=UTC
    restart: unless-stopped
